[build]
  command = "pnpm run build"
  publish = "dist-preview"

[[redirects]]
  from = "/api/*"
  to = "http://162.141.109.127:3456/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "noindex"
